name: check-requirements

on:
  push:
    tags:
    - build-*

jobs:
  check-requirements:
    name: Check Online installer
    runs-on: windows-latest
    #runs-on: self-hosted
    steps:
      - name: Install Python virtualenv
        run: python esp-idf/tools/idf_tools.py install-python-env
        shell: pwsh
      - name: Download Installer
        run:  Invoke-WebRequest https://github.com/espressif/idf-installer/releases/download/online-2.6-beta-32/esp-idf-tools-setup-online-2.6-beta-32.exe -OutFile installer.exe
        shell: pwsh
      - name: Run installer
        run: ./installer.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /NOCANCEL /NORESTART /IDFVERSION=v4.2
        shell: pwsh
      #- name: Build the project
      #  run: cd ${{ github.workspace }}/project ; . $env:IDF_PATH/export.ps1; $env:IDF_CCACHE_ENABLE=''; git submodule update --init --recursive; idf.py fullclean; idf.py build
      #  shell: pwsh
