name: check-requirements

on:
  push:
    tags:
    - build-*

jobs:
  check-requirements:
    name: Check build requirements
    runs-on: windows-latest
    env:
      IDF_PATH: ${{ github.workspace }}/esp-idf
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v2
        with:
          path: project
          repository: ctag-fh-kiel/ctag-tbd
          submodules: true
      - name: Checkout ESP-IDF repository
        uses: actions/checkout@v2
        with:
          path: esp-idf
          ref: v4.1.1
          repository: espressif/esp-idf
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Download dependencies
        run: cd esp-idf; install.bat
        shell: pwsh
      - name: Build the project
        run: cd ${{ github.workspace }}/project ; . $env:IDF_PATH/export.ps1; idf.py build
        shell: pwsh
