name: check-requirements

on: push

jobs:
  check-requirements:
    name: Check Python requirements
    runs-on: windows-latest
    # Windows Containers are not supported by GitHub Actions
    # It's necessary to install Python manually
    #container: python:3.7.9-windowsservercore

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Prepare download folder
        run: mkdir download
        shell: pwsh
      - name: Install build dependencies
        run: pip install wheel
      - name: Build wheel for greenlet
        run: python -m pip wheel --find-links download greenlet; $cache=pip cache dir; Get-ChildItem -Path $cache 'greenlet*.whl' -Recurse | % {Copy-Item -Path $_.FullName -Destination download -Container };
      - name: Build wheel for gevent
        run: python -m pip wheel --find-links download --only-binary greenlet "gevent<2.0,>=1.2.2"; $cache=pip cache dir; Get-ChildItem -Path $cache 'gevent*.whl' -Recurse | % {Copy-Item -Path $_.FullName -Destination download -Container }; ls download
      - name: Download requirements
        run: pip download --only-binary greenlet --only-binary gevent --only-binary cryptography --find-links download --dest download -r .\requirements.txt
      - name: Install requirements
        run: python -m pip install --no-index --find-links download -r .\requirements.txt
      - name: Write version of package to file
        run: python -c  "print('idf4.2_py3.9', file=open('download/version.txt', 'w'))"
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: idf4.2_py3.9_wheels
          path: download/