name: check-requirements

on: push

jobs:
  check-requirements:
    name: Check Python requirements
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Prepare download folder
        run: mkdir download
        shell: pwsh
      - name: Download requirements
        run: pip download --only-binary ":all:" --no-binary future --dest download -r .\requirements.txt
      - name: Run Bundle script
        run: python -m pip install --no-index --find-links download -r .\requirements.txt
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: idf4.2_py3.7_wheels
          path: download/
