name: check-requirements

on:
  push:
    tags:
    - build-*

jobs:
  check-requirements:
    name: Check build requirements
    #runs-on: windows-latest
    runs-on: self-hosted
    env:
      IDF_PATH: ${{ github.workspace }}/esp-idf
      #IDF_CCACHE_ENABLE: '' # This does not work here, export.ps1 will override it
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v2
        with:
          path: project
          repository: ctag-fh-kiel/ctag-tbd
          submodules: true
      - name: Checkout ESP-IDF repository
        uses: actions/checkout@v2
        with:
          path: esp-idf
          ref: v4.2
          repository: espressif/esp-idf
          submodules: true
      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: '3.8'
      - name: Install Python virtualenv
        run: python esp-idf/tools/idf_tools.py install-python-env
        shell: pwsh
      - name: Download dependencies
        run: python esp-idf/tools/idf_tools.py --non-interactive install
        shell: pwsh
      - name: Build the project
        # It's necessary to update submodule manually, otherwhise some submodule directories remains empty
        run: cd ${{ github.workspace }}/project ; . $env:IDF_PATH/export.ps1; $env:IDF_CCACHE_ENABLE=''; git submodule update --init --recursive; idf.py fullclean; idf.py build
        shell: pwsh
